apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: tooling
spec:
  ports:
    - port: 3306
  selector:
    app: tooling
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: tooling
spec:
  selector:
    matchLabels:
      app: tooling
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tooling
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: tooling
        - name: MYSQL_USER
          value: tooling
        - name: MYSQL_PASSWORD
          value: tooling
        ports:
        - containerPort: 3306
          name: mysql
